### ISSUE TITLE
Multi-Head

### ISSUE THREAD

**Issue by jinggaizi** [MenghaoGuo/-EANet#1]
how to Implement Multi-head

**Comment by MenghaoGuo** [comment]
Good Question.

Now, we do not design multi-head structure.  It is an important future work to design it.
Thanks for your attention.

**Comment by YouJiacheng** [comment]
我认为multi-head是本文提出的外部注意力机制的特殊情况，自注意力机制中multi-head的本质是将embedding映射到不同的空间后再求相似度。
在外部注意力机制中，backbone将像素转换为d维特征向量，而1个d维特征向量其实可以等价于m个d/m维特征向量，这m个特征向量已经在不同的空间中了；
然后，d维特征向量将与一组模板特征向量（M的行）求相似度，如果我们限制M具有某种稀疏性质，比如分块对角，就可以视为让模板特征向量也只在某一个空间中，也就是multi-head所要的。
当然，为了降低backbone的开销，可以用一个1×1卷积将特征向量升维（将特征向量经不同变换所得结果拼接与1×1卷积是等价的），而不是直接增大backbone的channel数量。
实际上自注意力机制的multi-head也只是更高维QK映射矩阵+更高维特征向量的特殊情况（分块对角+特征向量重复多次）。

**Comment by MenghaoGuo** [comment]
Recently, we design a multi-head attention and will release it in the next version.. Thanks.
