### ISSUE TITLE
关于EA的实现问题

### ISSUE THREAD

**Issue by last-one** [MenghaoGuo/-EANet#12]
感谢开源代码.

看到EA的代码里面这里一句,不知道有什么特殊考虑吗?
https://github.com/MenghaoGuo/-EANet/blob/de59e2535f92ce58648a217e21302e42296c8efd/model_torch.py#L198

谢谢~

**Comment by MenghaoGuo** [comment]
有的，初始化成一样是为了让 Mk 和 Mv 最开始时候是一致的，类似于 self-attention 里面的 K 和 V 都是从 X 来的，这种设置在训练初始阶段会稳定一些，但是貌似不会影响最终结果。
