### ISSUE TITLE
所以learnable Keys和Values是指全连接的weights吗？

### ISSUE THREAD

**Issue by 1338199** [MenghaoGuo/-EANet#13]

**Comment by futureisatyourhand** [comment]
hi, the code is 1*1 conv, not fc. Where is the FC?

**Comment by MenghaoGuo** [comment]
1*1 Conv1d/Conv2d are mathematically equal to FC.

**Comment by 1338199** [comment]
Perhaps I mistook the linear_0, linear_1 by the first sight,  so the conv1d's weights are the learnable keys and values mentioned by the paper?

**Comment by MenghaoGuo** [comment]
Yes, you get it.
