### ISSUE TITLE
Reproducing semantic segmentation result on PASCAL VOC

### ISSUE THREAD

**Issue by npurson** [MenghaoGuo/-EANet#15]
Not able to reproduce semantic segmentation result on PASCAL VOC val with MMSegmentation.
I used the code from <https://github.com/MenghaoGuo/-EANet/blob/main/model_torch.py> and modified nothing despite replacing the backbone with the one in MMSegmentation. After training EANet and PSPNet with several sets of configs, the result is that the mIoU of EANet is always a little bit below PSPNet, e.g. 73 vs 75.
Any suggestions?

**Comment by MenghaoGuo** [comment]
Thanks for your attention. 
We don't use mmsegmentation to train PASCAL VOC dataset. I suggest you can reproduce cityscapes or ADE20K results by using  mmsegmentation. 
If you want to reproduce PASCAL VOC results, i suggest to use https://github.com/XiaLiPKU/EMANet/ and replace it network.py, train.py, settings and eval.py by this repo. 
If you want to test the model directly. You can download the pretrain model and use test.py to get test results.
