### ISSUE TITLE
loss损失函数不降低

### ISSUE THREAD

**Issue by Mrbishuai** [MenghaoGuo/-EANet#16]
谢谢你的代码，我挺感兴趣你的课题。但是为什么我把external attention 嵌入到R3d网络中，epoch进行到很少轮之后loss就不再降低了，loss一直下不去。想向您请教请教。

**Comment by MenghaoGuo** [comment]
感谢您的关注，我们也非常希望看到视频上的相关实验。但是这么笼统的问题，我也不太清楚问题在哪，不知道您是否方便把您的代码贴出来，或者发我邮箱，非常希望与您谈探讨 external attention 在视频上的应用。
