### ISSUE TITLE
MLP in Segmentation

### ISSUE THREAD

**Issue by colorblank** [MenghaoGuo/-EANet#2]
Is mlp in this figure really linear layer? Or it is a conv1d layer.
![image](https://user-images.githubusercontent.com/16894837/117428082-4e441680-af58-11eb-9da3-f43ec09892da.png)

**Comment by MenghaoGuo** [comment]
Thanks for your attention. 
In my view, 1x1 kernel conv is equal to Linear Layer.

**Comment by colorblank** [comment]
Thanks. Are there multiple layers in MLP, or just one?

**Comment by RobinhoodKi** [comment]
Great works! Would you like to share the speed of inference on Cityscapes with 1024*2048 resolution input? Or make some comparison with the SOTA real-time semantic segmentation work like DDRNet, BiSegNetv2, etc?

**Comment by MenghaoGuo** [comment]
Good suggestions.
I will try to integrate this block into real-time semantic segmentation framework in the future. 
Thanks for your kind advice.
