### ISSUE TITLE
External_attention in the code is strange, only do attention on channel, but no attention on pixel.

### ISSUE THREAD

**Issue by zanonShao** [MenghaoGuo/-EANet#4]
Hello Menhao,
    I have some question about the difference between code and paper.
    In the paper, `'Equation (5) is the similarity between the i-th pixel and the j-th rows of M'`, external attention do the attention between pixels, however in the code I think `Conv1d` only can do the attention amount only one pixels’ channels, and pixels in _F_ not do attention with pixels in _M_.
    And in the paper `'In fact, we find that a small _S_, e.g. 64, works well in experiments.'` but in the code _d_ is setted to 64 instead of _S_.

**Comment by YouJiacheng** [comment]
M is a set of "pattern"  feature vectors (#vector = S), not feature vectors of pixels.
Conv1d.weight can be viewed as M, #out channel = S, # in channel = d. 
Therefore the result of Conv1d will be the dot product between feature vectors of pixels and M's rows(shape of M = S × d = out × in, out channels ↔ rows).
k in code = S in paper, c in code = d in paper.
等一下，为什么你要用英文提问，作者也是中国人啊。

**Comment by zanonShao** [comment]
ok, I get it.
谢谢你还先用英文回答🤣
