### ISSUE TITLE
能和self-attention模块一样多层堆叠形成深度网络吗？

### ISSUE THREAD

**Issue by YouJiacheng** [MenghaoGuo/-EANet#7]
似乎会很快地丢失信息。

**Comment by MenghaoGuo** [comment]
是否丢失信息取决于 External attention 里面的 s 的大小，如果把 s 设置成合理的大小，配合上合理的结构，应该是可以的。

**Comment by YouJiacheng** [comment]
> 是否丢失信息取决于 External attention 里面的 s 的大小，如果把 s 设置成合理的大小，配合上合理的结构，应该是可以的。
论文提到T2T-ViT可以把transformer模块换成EA，是不是已经说明可以堆叠了。
不过我提问的时候忘记EA是残差结构了，有shortcut存在理论上是不会丢失信息的吧。

**Comment by YouJiacheng** [comment]
😂学长好，我还是too young too simple，对相关工作的理解还是比较naive，而且GitHub交流效率也还可以（毕竟也没有很多人提issue，不至于影响版面）

**Comment by MenghaoGuo** [comment]
不是的，我们并没有替换 T2T-VIT 里面的所有 multi-head attention，只是替换了 T2T-Transformer 里的部分，T2T-backbone 里的没有更换。
